In [2]:
import os, sys
sys.path.append(os.getcwd() + "/../")
import notebook_utils
from experiments_utils import TwoQZeroPlusExperimentID

In [3]:
experiments = [TwoQZeroPlusExperimentID.HCXH2, TwoQZeroPlusExperimentID.HCXH, TwoQZeroPlusExperimentID.TWOQ, TwoQZeroPlusExperimentID.TWOQ2]

In [4]:
from experiments_utils import load_all_lambdas
import pandas as pd

experiment_ids = []
hardware_specs = []
embedding_indices = []
horizons = []
lambdas = []
for experiment_id in experiments:
    expr_lambdas = load_all_lambdas(experiment_id)
    
    for (hardware_spec, embedding_dict) in expr_lambdas.items():
        for (embedding_index, horizon_dict) in embedding_dict.items():
            for (horizon, lam) in horizon_dict.items():
                experiment_ids.append(experiment_id.value)
                hardware_specs.append(hardware_spec.value)
                embedding_indices.append(embedding_index)
                horizons.append(horizon)
                lambdas.append(lam)
                
all_lambdas = pd.DataFrame.from_dict({
            'experiment': experiment_ids,
            'hardware_spec': hardware_specs,
            'embedding_index': embedding_indices,
            'horizon': horizons,
            'guarantee': lambdas
        }) 
all_lambdas

     experiment    hardware_spec  embedding_index  horizon  guarantee
0         hcxh2     fake_algiers                0        2   0.846286
1         hcxh2     fake_algiers                0        3   0.846286
2         hcxh2     fake_algiers                0        4   0.846286
3         hcxh2     fake_algiers                0        5   0.846286
4         hcxh2     fake_algiers                0        6   0.846286
...         ...              ...              ...      ...        ...
3599      twoq2  fake_washington                4        5   0.846567
3600      twoq2  fake_washington                5        2   0.843953
3601      twoq2  fake_washington                5        3   0.843953
3602      twoq2  fake_washington                5        4   0.851100
3603      twoq2  fake_washington                5        5   0.851100

[3604 rows x 5 columns]

In [5]:
df_pivoted = all_lambdas.pivot(
    index=['hardware_spec', 'embedding_index', 'horizon'],
    columns='experiment',
    values='guarantee'
).reset_index()
df_pivoted

experiment,hardware_spec,embedding_index,horizon,hcxh,hcxh2,twoq,twoq2
0,fake_algiers,0,2,0.846302,0.846286,NaN,0.846301
1,fake_algiers,0,3,0.846302,0.846286,0.846286,0.846302
2,fake_algiers,0,4,0.846302,0.846286,0.846286,0.852819
3,fake_algiers,0,5,0.846302,0.846286,0.846286,0.852819
4,fake_algiers,0,6,0.846302,0.846286,NaN,NaN
...,...,...,...,...,...,...,...
1055,fake_yorktown,2,2,0.644976,0.644951,NaN,0.644976
1056,fake_yorktown,2,3,0.731157,0.731153,0.663199,0.730792
1057,fake_yorktown,2,4,0.822698,0.822670,0.730786,0.730793
1058,fake_yorktown,2,5,0.822698,0.830309,0.730789,0.743225
1059,fake_yorktown,2,6,0.822698,0.840054,NaN,NaN

In [6]:
df_pivoted["h-h2"] = df_pivoted.hcxh - df_pivoted.hcxh2
df_pivoted["h-q"] = df_pivoted.hcxh - df_pivoted.twoq
df_pivoted["h-q2"] = df_pivoted.hcxh - df_pivoted.twoq2
df_pivoted["h2-q"] = df_pivoted.hcxh2 - df_pivoted.twoq
df_pivoted["h2-q2"] = df_pivoted.hcxh2 - df_pivoted.twoq2
df_pivoted["q-q2"] = df_pivoted.twoq - df_pivoted.twoq2

In [7]:
df_pivoted.to_csv("all_lambdas.csv")

In [8]:

df_pivoted[df_pivoted.hcxh != df_pivoted.hcxh2].to_csv("temp.csv")